### ISSUE TITLE
 episodes = eval_py_env.get_stored_episodes()

### ISSUE THREAD

**Issue by seung-kim** [StanfordVL/GibsonSim2RealChallenge#2]
Hi, 

in train_eval.py, there's this line for evaluation:
 episodes = eval_py_env.get_stored_episodes()

But it seems like 'get_stored_episodes' is not defined.
Could you check this please?

**Comment by fxia22** [comment]
We pushed the fix, you can either `docker pull gibsonchallenge/gibsonv2` or do `git pull origin gibson_sim2real` in `/opt/agents` and `/opt/GibsonEnvV2`. 

As the challenges goes by we might push other updates that facilitate training. The updates will be backward-compatible.
