### ISSUE TITLE
can't running in server without GPU

### ISSUE THREAD

**Issue by WSPeng** [StanfordVL/GibsonSim2RealChallenge#3]
Hi, I tried to run the docker in a server without GPU, but with error "Unable to initialize EGL". 
I checked that Gibsonv2 environment requires GPU, so I assume for this challenge, a server without GPU won't work, am i right?

thanks

**Comment by fxia22** [comment]
Hi @WSPeng, yes, gibson2 requires a GPU to run the rendering. If you have a workstation/server with GPU, you would need to install `nvidia-docker` and the sanity check would be to run `docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi`

If you can pass this sanity check, you should be able to run gibson2

**Comment by WSPeng** [comment]
Thanks, I will try it as soon as I got a server with GPU.
