### ISSUE TITLE
Issue downloading `gibson-challenge-dataset`

### ISSUE THREAD

**Issue by vishsangale** [StanfordVL/GibsonSim2RealChallenge#6]
I followed the instructions from [here](https://docs.google.com/forms/d/e/1FAIpQLSen7LZXKVl_HuiePaFzG_0Boo6V3J5lJgzt3oPeSfPr4HTIEA/viewform) to download the dataset, also signed the agreement, but I can not download the `gibson-challenge-data`, It errors out with `Forbidden Error 403`. I can download the Gibson env v1 and v2 data as well as the dataset for habitat.

**Comment by fxia22** [comment]
@vishsangale  Just updated, can you try again? Thanks!

**Comment by vishsangale** [comment]
Thank you very much! I could successfully download the data.
