### ISSUE TITLE
Disable rendering of env on headless machines

### ISSUE THREAD

**Issue by vishsangale** [StanfordVL/GibsonSim2RealChallenge#7]
Hi, 

I see that GibsonEnvV2 is rendering the scene while training the algorithm. I was wondering if there is a way to disable this rendering on headless machines while training. According to http://svl.stanford.edu/gibson2/docs/quickstart.html#environment-configuration I tried to use `headless` mode in `/gibson-challenge-data/locobot_p2p_nav_house.yaml` but it seems like it still stuck while initializing EGL. I wonder if I am changing the correct config.

`WARNING:tensorflow:From /miniconda/envs/gibson/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
W0323 17:32:20.540694 140284188145472 deprecation.py:506] From /miniconda/envs/gibson/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
I0323 17:32:20.542290 140284188145472 parallel_py_environment.py:82] Spawning all processes.
device 0 is not available for rendering
device index is larger than number of devices, falling back to use 0
Unable to initialize EGL`

Still investigating if EGL could access the GPU. I could run nvidia-smi in the docker.

**Comment by fxia22** [comment]
In `headless` mode EGL is still needed for rendering the frames for the robots. Your issue looks like EGL cannot access GPU, or the GPU cannot be used for rendering. What GPU and driver version are you using? Can you check for common issues listed here? http://svl.stanford.edu/gibson2/docs/issues.html

**Comment by fxia22** [comment]
`gibson2/core/render/mesh_renderer/build/query_devices` gets the available devices for EGL to use for rendering, looks like it is returning 0 in your case. Indicating no available devices can be used.

**Comment by vishsangale** [comment]
Seems like an issue was with the nvidia-cuda-mps-server which did not start on boot and which led to not detect devices in docker. After manually starting could run the pipeline. Thanks for your pointer.
